# Generated by Django 4.2.1 on 2023-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_asset_name_asset_checkedoutcondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
