# Generated by Django 4.2.1 on 2023-06-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_asset_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='newCondition',
            new_name='returnCondition',
        ),
    ]
